apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gameplane
rules:
  # Gameplane custom resources
  - apiGroups:
      - gameplane.kubelize.io
    resources: 
      - xgameservers
      - xsdtdgameservers
      - gameservers
    verbs:
      - '*'
  # Core Kubernetes resources needed by compositions
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - secrets
      - persistentvolumeclaims
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # Apps resources for deployments
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # Networking resources for ingresses
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gameplane-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gameplane
subjects:
  - kind: ServiceAccount
    name: provider-kubernetes
    namespace: crossplane-system


